version: '3.0'

services:
  dw-dev-database:
    image: mongo
    container_name: dw-dev-database
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongo-volume:/data/db
volumes:
  mongo-volume: